Update pl.json
music-assistant/hass-music-assistant pull request #718
Opened 2022-07-23 22:05 UTC by LukaszP2

Revision Alignment

2022-07-23 22:14 UTC, marcelveldt commented
I've noticed there are untranslated English strings in the file. Please remove them so only the polish strings are in the file.
That way the translation system will fallback to the default english strings

2022-07-25 16:39 UTC, marcelveldt requested changes
Please remove the non translated strings or translate them.
Thanks!

2022-07-26 04:31 UTC, LukaszP2 reviewed
It is all

2022-07-27 18:50 UTC, marcelveldt approved these changes

2022-07-27 18:50 UTC, merged